UPSTREAM: <carry>: Explicitly include mockgen model package in vendor directory
Include the `github.com/golang/mock/mockgen/model` package as an explicit dependency
to support the mockgen utility. This change is necessary due to the rebasing to v2.8.2
and the downstream fork's reliance on the vendor directory for building the controller image in CI.
Without this explicit inclusion, the package lookup fails with the error:
"cannot find module providing package...import lookup disabled by -mod=vendor".